[package]
name = "tweenkit"
version = "0.1.0"
authors = ["Hugh Lang <hughlang@gmail.com>"]
edition = "2018"

[lib]
name = "tween"
path = "src/lib.rs"

[[bin]]
name = "ggrunner"
path = "examples/ggez/ggrunner.rs"

[[bin]]
name = "ggease"
path = "examples/ggez/ggease.rs"

[[bin]]
name = "ggtimeline"
path = "examples/ggez/ggtimeline.rs"

[[bin]]
name = "ggtween1"
path = "examples/ggez/ggtween1.rs"

[features]
default = []
wasm = []

[dependencies]
cgmath = "0.17.0"
uuid = { version = "0.7", features = ["v4"] }
unwrap_to = "0.1.0"
ggez = { git = "https://github.com/hughlang/ggez.git" }
# ggez = { path = "../ggez-fork" }
# ggez = "0.5.0"

