[package]
name = "tweenkit"
version = "0.1.0"
authors = ["Hugh Lang <hughlang@gmail.com>"]
edition = "2018"

[lib]
name = "tween"
path = "src/lib.rs"

# [[bin]]
# name = "mouse"
# path = "examples/animate/mouse.rs"
#
# [[bin]]
# name = "boxdemo"
# path = "examples/animate/boxdemo.rs"
#
# [[bin]]
# name = "tween0"
# path = "examples/animate/tween0.rs"

[[bin]]
name = "channel"
path = "examples/orb/channel.rs"

[[bin]]
name = "crossbeam"
path = "examples/orb/crossbeam.rs"

[[bin]]
name = "drawing"
path = "examples/orb/drawing.rs"

[[bin]]
name = "dragging"
path = "examples/orb/dragging.rs"

[features]
default = []
wasm = []

[dependencies]
cgmath = "0.17.0"
unwrap_to = "0.1.0"
# tokio = "0.1"
crossbeam-channel = "0.3"
crossbeam-utils = "0.6.5"

# timer = "0.2.0"
orbrender = { path = "../orbrender" }
# sdl2 = { path = "../rust-sdl2" }

