[package]
name = "tweek-rust"
description = "A tween animation library for Rust"
version = "0.2.0"
authors = ["Hugh Lang <hughlang@gmail.com>"]
keywords = ["animation", "graphics", "gui"]
license = "LGPL"
readme = "README.md"
repository = "https://github.com/wasm-network/tweek-rust"
exclude = ["resources/*"]
edition = "2018"

[lib]
name = "tweek"
path = "src/lib.rs"

# [[example]]
# name = "basics"
# path = "examples/ggez/gg_basics.rs"

# [[example]]
# name = "demos"
# path = "examples/ggez/gg_demos.rs"

# [[example]]
# name = "player"
# path = "examples/ggez/gg_player.rs"

# [[example]]
# name = "gui"
# path = "examples/ggez/gg_gui.rs"

[[example]]
name = "test"
path = "examples/quicksilver/qs_test.rs"

[[example]]
name = "basics"
path = "examples/quicksilver/qs_basics.rs"

[[example]]
name = "gui"
path = "examples/quicksilver/gui.rs"

[dependencies]
quicksilver = "*"
# quicksilver = { path = "../quick-fork" }
cgmath = "0.17.0"
log = "0.4"
rand = "0.6"
uuid = { version = "0.7", features = ["v4"] }
unwrap_to = "0.1.0"
ggez = "^0.5.0-rc.1"
glyph_brush = "0.4"
# glyph_brush = { path = "../glyph-brush/glyph-brush" }
image = { version = "0.21", default-features = false, features = ["png_codec"] }
# image = { path = "../image" }
immi = { version = "1.0" }

[dev-dependencies]
env_logger = "0.6"
color-backtrace = { version = "0.1" }