[package]
name = "tweenkit"
version = "0.1.0"
authors = ["Hugh Lang <hughlang@gmail.com>"]
edition = "2018"

[lib]
name = "tween"
path = "src/lib.rs"

# [[bin]]
# name = "mouse"
# path = "examples/animate/mouse.rs"
#
# [[bin]]
# name = "boxdemo"
# path = "examples/animate/boxdemo.rs"
#
[[bin]]
name = "ggease"
path = "examples/ggez/ggease.rs"

[[bin]]
name = "ggtween1"
path = "examples/ggez/ggtween1.rs"

[features]
default = []
wasm = []

[dependencies]
cgmath = "0.17.0"
unwrap_to = "0.1.0"
enum_derive = "0.1.7"
custom_derive = "0.1.1"
# ggez = { path = "../ggez" }
ggez = "0.5.0-rc.0"

