[package]
name = "tweek-rust"
version = "0.1.0"
authors = ["Hugh Lang <hughlang@gmail.com>"]
edition = "2018"

[lib]
name = "tweek"
path = "src/lib.rs"

[[example]]
name = "basics"
path = "examples/ggez/gg_basics.rs"

[[example]]
name = "demos"
path = "examples/ggez/gg_demos.rs"

[[example]]
name = "player"
path = "examples/ggez/gg_player.rs"

[dependencies]
cgmath = "0.17.0"
log = "0.4"
rand = "0.6"
uuid = { version = "0.7", features = ["v4"] }
unwrap_to = "0.1.0"
ggez = "0.5.0-rc.1"
# ggez = { git = "https://github.com/ggez/ggez.git" }

[dev-dependencies]
env_logger = "0.6"