[package]
name = "tweek-rust"
version = "0.1.0"
authors = ["Hugh Lang <hughlang@gmail.com>"]
edition = "2018"

[lib]
name = "tweek"
path = "src/lib.rs"

[[bin]]
name = "ggmix"
path = "examples/ggez/ggmix.rs"

[[bin]]
name = "ggsequence"
path = "examples/ggez/ggsequence.rs"

[[bin]]
name = "ggtransform"
path = "examples/ggez/ggtransform.rs"

[[bin]]
name = "ggease"
path = "examples/ggez/ggease.rs"

[[bin]]
name = "gg_demos"
path = "examples/ggez/gg_demos.rs"

[[bin]]
name = "gg_player"
path = "examples/ggez/gg_player.rs"

[dependencies]
cgmath = "0.17.0"
rand = "0.6"
uuid = { version = "0.7", features = ["v4"] }
unwrap_to = "0.1.0"
ggez = "0.5.0-rc.1"
# ggez = { git = "https://github.com/ggez/ggez.git" }
